
# 使用---表示一个新的配置块 , 可以折叠, 类似c#中的region
---
spring:
  threads:
    virtual:
      # 启用虚拟线程(JDK21)
      enabled: true
---
# web容器相关配置
server:
  port: 80
---
# 自定义属性注入配置
person:
  name: 张三
  age: 18
  birthDay: 2010/10/10 12:12:12
  like: true
  child:
    name: 李四
    age: 20
    #birthDay 推荐写为birth-day
    birth-day: 2018/10/10
    text: ["abc","def"]
  dogs:
    - name: 小黑
      age: 3
    - name: 小白
      age: 2
  cats:
    c1:
      name: 小蓝
      age: 3
    c2: {name: 小绿,age: 2} #对象也可用{}表示
    c3:
      #文本可以使用 | 开头，大文本写在下层，保留文本格式，换行符正确显示
      name: |
        使用|的文本,第一行
        第二行
        第三行
    c4:
      #文本可以使用 > 开头，大文本写在下层，折叠换行符
      name: >
        使用>的文本,第一行
        第二行
        第三行
---
#日志配置
logging:
  level:
    #指定包日志级别
    com.com.example: debug
    #全局日志级别
    root: info
  #指定日志文件输出路径,配置后日志会产生文件
  file:
    #日志文件路径
    path: logs/pathLog.log
    #日志文件名(指定路径和文件名时,仅文件名生效)
    name: nameLog.log
  #默认日志框架为logback , 若需要切换, 需要先排除
  logback:
    rollingpolicy:
      #日志存档的文件名格式（默认值：${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz）
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.log
      #应用启动时是否清除以前存档（默认值：false
      clean-history-on-start: false
      #存档前，每个日志文件的最大大小（默认值：10MB）
      max-file-size: 2KB
      #日志文件被删除之前，可以容纳的最大大小（默认值：0B）。设置1GB则磁盘存储超过 1GB 日志后就会删除旧日志文件
      total-size-cap: 1GB
      #日志文件保存的最大天数(默认值：7)
      max-history: 7
#自定义配置:将logback.xml或log4j2.xml(取决于实际使用的日志框架, 默认为logback)文件放入资源路径中
#建议在日志配置中使用-spring变量（例如，logback-spring.xml 而不是 logback.xml）。
#如果使用标准配置文件，spring 无法完全控制日志初始化。
#最佳实战：自己要写配置，配置文件名加上 xx-spring.xml
---
# 静态资源规则配置
spring:
  # spring.web下只有静态资源(resources)和国际化(locale)相关配置
  web:
    # 配置国际化
    locale: zh_CN
    # 配置静态资源
    resources:
      # 开启静态资源映射
      add-mappings: true
      #自定义静态资源文件夹位置
      static-locations: classpath:/static/,classpath:/public/,classpath:/resources/,classpath:/META-INF/resources/
      cache:
        # 静态资源缓存时间
        period: 3600
        # 是否使用Last-Modified响应头,对比文件修改时间(若相同返回304状态码)
        use-last-modified: true
        # 静态资源缓存详细合并配置, 会覆盖period配置
        cachecontrol:
          # 浏览器第一次请求服务器，服务器告诉浏览器此资源缓存7200秒，7200秒以内的所有此资源访问不用发给服务器请求，7200秒以后发请求给服务器
          max-age: 7200
          # 共享缓存
          cache-public: true
---
# mvc配置
spring:
  mvc:
#    # 配置webjar访问映射路径(前后端结合, 将js等静态文件以jar包形式保存管理依赖版本, 需要添加额外依赖, 官网: https://www.webjars.org/)
#    webjars-path-pattern: /webjars/**
    # 配置静态资源访问映射路径(例如,访问路径为/static/a/1.jpg,则会去spring.web.resources.static-locations配置指定的路径下查找)
    static-path-pattern: /static/**
    # 内容协商功能配置
    contentnegotiation:
      # 开启基于请求参数的内容协商功能。 默认参数名：format。 默认此功能不开启
      favor-parameter: true
      # 指定内容协商时使用的参数名。默认是 format, 例如: /user?format=xml, 此时返回xml格式内容
      parameter-name: format
      # 支持的媒体类型
      media-types:
        # 添加自定义yaml格式支持
        yaml: application/yaml